// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "https://your-agent.com/webhooks/slotflow",
 *         events: ["booking.confirmed", "booking.cancelled"]
 *     }
 */
export interface CreateWebhookRequest {
    /** URL to receive webhook POST requests (must be HTTPS in production) */
    url: string;
    /** Events to subscribe to */
    events: CreateWebhookRequest.Events.Item[];
}

export namespace CreateWebhookRequest {
    export type Events = Events.Item[];

    export namespace Events {
        export const Item = {
            BookingConfirmed: "booking.confirmed",
            BookingCancelled: "booking.cancelled",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
