// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         webhookId: "webhookId"
 *     }
 */
export interface DeleteWebhookRequest {
    /** The ID of the webhook to delete */
    webhookId: string;
}
