// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../../../../index.js";

/**
 * @example
 *     {
 *         humanId: "humanId",
 *         type: "block",
 *         title: "Holiday break",
 *         all_day: true,
 *         start_date: "2026-12-23",
 *         end_date: "2026-12-27"
 *     }
 *
 * @example
 *     {
 *         humanId: "humanId",
 *         type: "block",
 *         title: "Team standup",
 *         all_day: false,
 *         start_date: "2026-03-01",
 *         start_time: "14:00",
 *         end_time: "15:00",
 *         recurrence: {
 *             freq: "weekly",
 *             days: [2]
 *         }
 *     }
 *
 * @example
 *     {
 *         humanId: "humanId",
 *         type: "open",
 *         title: "Saturday overtime",
 *         all_day: false,
 *         start_date: "2026-03-01",
 *         start_time: "10:00",
 *         end_time: "14:00",
 *         recurrence: {
 *             freq: "weekly",
 *             days: [6]
 *         }
 *     }
 */
export interface CreateOverrideRequest {
    /** The ID of the human */
    humanId: string;
    /** `block` to remove availability, `open` to add extra availability */
    type: CreateOverrideRequest.Type;
    /** Descriptive label for this override */
    title: string;
    /** Set to true for full-day overrides. When false, start_time and end_time are required. */
    all_day: boolean;
    /** Start date (YYYY-MM-DD) */
    start_date: string;
    /** End date for multi-day overrides (YYYY-MM-DD). Optional. */
    end_date?: string;
    /** Required when all_day is false. HH:MM format in human's timezone. */
    start_time?: string;
    /** Required when all_day is false. HH:MM format in human's timezone. */
    end_time?: string;
    recurrence?: Slotflow.RecurrenceRule | null;
}

export namespace CreateOverrideRequest {
    /** `block` to remove availability, `open` to add extra availability */
    export const Type = {
        Block: "block",
        Open: "open",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
