// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         humanId: "humanId",
 *         overrideId: "overrideId"
 *     }
 */
export interface DeleteOverrideRequest {
    /** The ID of the human */
    humanId: string;
    /** The ID of the schedule override to delete */
    overrideId: string;
}
