// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         humanId: "humanId"
 *     }
 */
export interface ListOverridesRequest {
    /** The ID of the human */
    humanId: string;
}
