// This file was auto-generated by Fern from our API Definition.

export interface CancelBookingResponse {
    id?: string | undefined;
    status?: CancelBookingResponse.Status | undefined;
}

export namespace CancelBookingResponse {
    export const Status = {
        Cancelled: "cancelled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
