// This file was auto-generated by Fern from our API Definition.

export const ListBookingsRequestStatus = {
    Confirmed: "confirmed",
    Cancelled: "cancelled",
} as const;
export type ListBookingsRequestStatus = (typeof ListBookingsRequestStatus)[keyof typeof ListBookingsRequestStatus];
