// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../../../index.js";

export interface ListHumansResponse {
    humans?: Slotflow.Human[] | undefined;
    /** Total number of active humans */
    total?: number | undefined;
}
