// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "Sarah Chen",
 *         email: "sarah@acme.com",
 *         role: "sales_rep",
 *         timezone: "America/New_York"
 *     }
 */
export interface CreateHumanRequest {
    /** Full name of the human */
    name: string;
    /** Email address (optional) */
    email?: string;
    /** Role or title (optional, e.g. "sales_rep", "interviewer") */
    role?: string;
    /** IANA timezone identifier (e.g. "America/New_York", "Europe/London") */
    timezone: string;
}
