// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../../../index.js";

export interface ListOverridesResponse {
    overrides?: Slotflow.ScheduleOverride[] | undefined;
    total?: number | undefined;
}
