// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../../../index.js";

export interface ListWebhooksResponse {
    webhooks?: Slotflow.Webhook[] | undefined;
    total?: number | undefined;
}
