// This file was auto-generated by Fern from our API Definition.

export interface ApiError {
    error?: ApiError.Error_ | undefined;
}

export namespace ApiError {
    export interface Error_ {
        /** Machine-readable error code */
        code?: Error_.Code | undefined;
        /** Human-readable error description */
        message?: string | undefined;
        /** HTTP status code */
        status?: number | undefined;
    }

    export namespace Error_ {
        /** Machine-readable error code */
        export const Code = {
            Unauthorized: "UNAUTHORIZED",
            NotFound: "NOT_FOUND",
            SlotUnavailable: "SLOT_UNAVAILABLE",
            InvalidDuration: "INVALID_DURATION",
            OutsideWorkingHours: "OUTSIDE_WORKING_HOURS",
            ScheduleBlocked: "SCHEDULE_BLOCKED",
            LimitReached: "LIMIT_REACHED",
            ValidationError: "VALIDATION_ERROR",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
