// This file was auto-generated by Fern from our API Definition.

/**
 * The human's base weekly schedule. Null if not yet configured.
 */
export interface AvailabilityRules {
    /** Days of the week the human works. 1=Monday, 2=Tuesday, ..., 7=Sunday. */
    working_days: number[];
    /** Start of working hours in HH:MM format (in human's timezone) */
    work_start: string;
    /** End of working hours in HH:MM format (in human's timezone) */
    work_end: string;
    /** Allowed meeting durations in minutes */
    meeting_durations: number[];
}
