// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../index.js";

export interface BookingsListResponse {
    bookings?: Slotflow.Booking[] | undefined;
    /** Total matching bookings (for pagination) */
    total?: number | undefined;
    /** Number of results returned */
    limit?: number | undefined;
    /** Number of results skipped */
    offset?: number | undefined;
}
