// This file was auto-generated by Fern from our API Definition.

export interface Booking {
    id?: string | undefined;
    human_id?: string | undefined;
    /** Booking start time in UTC */
    starts_at?: string | undefined;
    /** Booking end time in UTC */
    ends_at?: string | undefined;
    /** Duration in minutes */
    duration_minutes?: number | undefined;
    /** Name of the person being booked */
    attendee_name?: string | undefined;
    /** Email of the attendee (optional) */
    attendee_email?: (string | null) | undefined;
    status?: Booking.Status | undefined;
    /** Arbitrary JSON metadata passed by your agent for workflow tracking */
    metadata?: Record<string, unknown> | undefined;
    created_at?: string | undefined;
}

export namespace Booking {
    export const Status = {
        Confirmed: "confirmed",
        Cancelled: "cancelled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
