// This file was auto-generated by Fern from our API Definition.

export interface Human {
    /** Unique identifier for the human */
    id: string;
    /** Full name of the human */
    name: string;
    /** Email address (optional) */
    email?: (string | null) | undefined;
    /** Role or title (e.g. "sales_rep", "interviewer") */
    role?: (string | null) | undefined;
    /** IANA timezone identifier (e.g. "America/New_York") */
    timezone: string;
    /** Whether the human is active and bookable */
    active: boolean;
    /** ISO 8601 creation timestamp */
    created_at: string;
}
