// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../index.js";

export interface HumanWithAvailability extends Slotflow.Human {
    availability_rules?: (Slotflow.AvailabilityRules | null) | undefined;
}
