// This file was auto-generated by Fern from our API Definition.

/**
 * Defines a recurring pattern for schedule overrides. Null for one-time overrides.
 */
export interface RecurrenceRule {
    /** Recurrence frequency */
    freq?: RecurrenceRule.Freq | undefined;
    /** Repeat every N periods (default 1). Set to 2 for bi-weekly. */
    interval?: number | undefined;
    /** For weekly: which days (1=Monday, 7=Sunday). E.g. [2, 4] for Tuesday and Thursday. */
    days?: number[] | undefined;
    /** For monthly by date: which day of the month (e.g. 15 for the 15th) */
    day_of_month?: number | undefined;
    /** For monthly by week: which week (1=first, 5=last) */
    week?: number | undefined;
    /** For monthly by week+day: which day (1=Monday, 7=Sunday) */
    day?: number | undefined;
}

export namespace RecurrenceRule {
    /** Recurrence frequency */
    export const Freq = {
        Weekly: "weekly",
        Monthly: "monthly",
    } as const;
    export type Freq = (typeof Freq)[keyof typeof Freq];
}
