// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../index.js";

export interface ScheduleOverride {
    id?: string | undefined;
    human_id?: string | undefined;
    /** `block` removes availability, `open` adds extra availability */
    type?: ScheduleOverride.Type | undefined;
    /** Descriptive label (e.g. "Holiday break", "Saturday overtime") */
    title?: string | undefined;
    /** Whether this override applies to the entire day */
    all_day?: boolean | undefined;
    /** Start date (YYYY-MM-DD) */
    start_date?: string | undefined;
    /** End date for multi-day overrides (YYYY-MM-DD). Null for single-day. */
    end_date?: (string | null) | undefined;
    /** Start time in HH:MM format. Null when all_day is true. */
    start_time?: (string | null) | undefined;
    /** End time in HH:MM format. Null when all_day is true. */
    end_time?: (string | null) | undefined;
    recurrence?: (Slotflow.RecurrenceRule | null) | undefined;
    created_at?: string | undefined;
}

export namespace ScheduleOverride {
    /** `block` removes availability, `open` adds extra availability */
    export const Type = {
        Block: "block",
        Open: "open",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
