// This file was auto-generated by Fern from our API Definition.

export interface Slot {
    /** Slot start time in UTC */
    starts_at?: string | undefined;
    /** Slot end time in UTC */
    ends_at?: string | undefined;
}
