// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../index.js";

export interface SlotsResponse {
    human_id?: string | undefined;
    /** Requested duration in minutes */
    duration?: number | undefined;
    /** Human's IANA timezone (informational, for display conversion) */
    timezone?: string | undefined;
    /** Available time slots, sorted by start time. Empty array if no availability. */
    slots?: Slotflow.Slot[] | undefined;
    /** Number of available slots */
    total?: number | undefined;
}
