// This file was auto-generated by Fern from our API Definition.

export interface Webhook {
    id?: string | undefined;
    /** URL that receives webhook POST requests */
    url?: string | undefined;
    /** Events this webhook subscribes to */
    events?: Webhook.Events.Item[] | undefined;
    /** HMAC-SHA256 signing secret for verifying webhook payloads. Prefixed with `whsec_`. Store this securely — it is only returned when creating or listing webhooks. */
    signing_secret?: string | undefined;
    active?: boolean | undefined;
    created_at?: string | undefined;
}

export namespace Webhook {
    export type Events = Events.Item[];

    export namespace Events {
        export const Item = {
            BookingConfirmed: "booking.confirmed",
            BookingCancelled: "booking.cancelled",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
