// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../index.js";

/**
 * The payload POSTed to your webhook URL when a booking event occurs.
 */
export interface WebhookPayload {
    event?: WebhookPayload.Event | undefined;
    created_at?: string | undefined;
    data?: Slotflow.Booking | undefined;
}

export namespace WebhookPayload {
    export const Event = {
        BookingConfirmed: "booking.confirmed",
        BookingCancelled: "booking.cancelled",
    } as const;
    export type Event = (typeof Event)[keyof typeof Event];
}
