// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         bookingId: "bookingId"
 *     }
 */
export interface CancelBookingRequest {
    /** The ID of the booking to cancel */
    bookingId: string;
}
