// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         human_id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
 *         starts_at: "2026-03-10T14:00:00Z",
 *         duration: 30,
 *         attendee_name: "Alex Rivera",
 *         attendee_email: "alex@startup.io",
 *         metadata: {
 *             "lead_id": "lead_8294",
 *             "conversation_id": "conv_1847",
 *             "source": "ai_sdr"
 *         }
 *     }
 */
export interface CreateBookingRequest {
    /** ID of the human to book */
    human_id: string;
    /** Booking start time in ISO 8601 UTC format */
    starts_at: string;
    /** Meeting duration in minutes. Must match one of the human's meeting_durations. */
    duration: number;
    /** Name of the person being booked */
    attendee_name: string;
    /** Email of the attendee (optional) */
    attendee_email?: string;
    /** Arbitrary JSON for your agent's workflow state (lead IDs, conversation IDs, etc.) */
    metadata?: Record<string, unknown>;
}
