// This file was auto-generated by Fern from our API Definition.

import type * as Slotflow from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListBookingsRequest {
    /** Filter by human ID */
    human_id?: string;
    /** Filter by booking status */
    status?: Slotflow.ListBookingsRequestStatus;
    /** Filter bookings starting on or after this date */
    date_from?: string;
    /** Filter bookings starting on or before this date */
    date_to?: string;
    /** Number of results to return (default 50, max 100) */
    limit?: number;
    /** Number of results to skip for pagination (default 0) */
    offset?: number;
}
