// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         humanId: "humanId",
 *         date_from: "2026-03-10",
 *         date_to: "2026-03-14",
 *         duration: 1
 *     }
 */
export interface GetAvailableSlotsRequest {
    /** The ID of the human */
    humanId: string;
    /** Start of date range (inclusive) */
    date_from: string;
    /** End of date range (inclusive) */
    date_to: string;
    /** Meeting duration in minutes. Must match one of the human's configured `meeting_durations`. */
    duration: number;
}
