// This file was auto-generated by Fern from our API Definition.

import { AvailabilityClient } from "./api/resources/availability/client/Client.js";
import { BookingsClient } from "./api/resources/bookings/client/Client.js";
import { HumansClient } from "./api/resources/humans/client/Client.js";
import { ScheduleOverridesClient } from "./api/resources/scheduleOverrides/client/Client.js";
import { SlotsClient } from "./api/resources/slots/client/Client.js";
import { WebhooksClient } from "./api/resources/webhooks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace SlotflowClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SlotflowClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SlotflowClient.Options>;
    protected _humans: HumansClient | undefined;
    protected _availability: AvailabilityClient | undefined;
    protected _scheduleOverrides: ScheduleOverridesClient | undefined;
    protected _slots: SlotsClient | undefined;
    protected _bookings: BookingsClient | undefined;
    protected _webhooks: WebhooksClient | undefined;

    constructor(options: SlotflowClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get humans(): HumansClient {
        return (this._humans ??= new HumansClient(this._options));
    }

    public get availability(): AvailabilityClient {
        return (this._availability ??= new AvailabilityClient(this._options));
    }

    public get scheduleOverrides(): ScheduleOverridesClient {
        return (this._scheduleOverrides ??= new ScheduleOverridesClient(this._options));
    }

    public get slots(): SlotsClient {
        return (this._slots ??= new SlotsClient(this._options));
    }

    public get bookings(): BookingsClient {
        return (this._bookings ??= new BookingsClient(this._options));
    }

    public get webhooks(): WebhooksClient {
        return (this._webhooks ??= new WebhooksClient(this._options));
    }
}
