// This file was auto-generated by Fern from our API Definition.

export const SlotflowEnvironment = {
    Production: "https://api.slotflow.dev",
} as const;

export type SlotflowEnvironment = typeof SlotflowEnvironment.Production;
