// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         humanId: "humanId",
 *         working_days: [1, 2, 3, 4, 5],
 *         work_start: "09:00",
 *         work_end: "17:00",
 *         meeting_durations: [30, 60]
 *     }
 */
export interface SetAvailabilityRequest {
    /** The ID of the human */
    humanId: string;
    /** Days of the week. 1=Monday through 7=Sunday. */
    working_days: number[];
    /** Start of working hours in HH:MM format (in human's timezone) */
    work_start: string;
    /** End of working hours in HH:MM format (in human's timezone) */
    work_end: string;
    /** Allowed meeting durations in minutes */
    meeting_durations: number[];
}
